exclude: ['README.md']

theme: jekyll-theme-primer

title: learnlatex.org
description: Learn LaTeX on-line

<<<<<<< HEAD
logo: learnlatex-logo.png
=======
logo: learnlatex.png

plugins:
  - jekyll-sitemap

kramdown:
    syntax_highlighter_opts:
      disable: true

latex: "<span>L<span style='font-variant: small-caps; vertical-align:.35ex;margin-left:-.15em;margin-right:-.05em;'>a</span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
tex: "<span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
<<<<<<< HEAD
<<<<<<< HEAD

>>>>>>> 5cf5ffe2... Updated logo files
=======
>>>>>>> 92eaef88... Try auto-generating a sitemap
=======

langs:
   - en
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2de37f8a... language switching
=======
   - de
   - fr
   - pt
<<<<<<< HEAD
=======
   - ja
=======
   - fr
   - pt
>>>>>>> d3fffecf... drop incomplete translations from the menu #92
   - vi
<<<<<<< HEAD
   - zh-Hans
>>>>>>> 2b8821e5... add zh-Hans and adjust JavaScript and liquid as language code not two letter
=======
   - es


>>>>>>> cbfa4b58... add zh-Hans and adjust JavaScript and liquid as language code not two letter

>>>>>>> b3cec993... language stubs
